# DNUM - Staging (layer de base pour les autres projets métiers)
Staging:
  target: local
  outputs:
    anais:
      type: postgres
      host: 10.89.136.17
      user: staging_admin
      password: "{{ env_var('DBT_DB_PASSWORD') }}"
      port: 5432
      schema: public
      dbname: staging
    local:
      type: duckdb
      path: data/duckdb_database.duckdb
      schema: main

CertDC:
  target: local
  outputs:
    anais:
      type: postgres
      host: 10.89.136.17
      user: certelec_dc_admin
      # password: "{{ env_var('DBT_DB_PASSWORD') }}"
      password: "UQ=#7I)fp$_C8u"
      port: 5432
      schema: public
      dbname: certelec_dc
    local:
      type: duckdb
      path: data/duckdb_database.duckdb
      schema: main
  
      

# DNUM - Layer InspectionControle (dépend de la base de Staging)
dbtInspectionControle:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../../Staging/data/duckdb_database.duckdb
      schema: main

# DNUM - Layer Helios (dépend de la base de Staging)
Helios:
  target: local
  outputs:
    local:
      type: duckdb
      path: data/duckdb_database.duckdb
      schema: main