version: 2

# Sources pour DuckDB
sources:
  - name: main
    tables:
      - name: cert_dc_insern_2023_2024
      - name: cert_dc_insern_n2_n1
      - name: cert_dc_insern
      - name: dc_det
      - name: sa_esms
      - name: sa_hubee
      - name: sa_insee_histo
      - name: sa_pmsi
      - name: sa_rpu
      - name: sa_t_finess
      - name: sa_usld
      - name: v_commune_depuis
      - name: v_commune
      - name: v_departement
      - name: v_region

# Sources pour PostgreSQL
  - name: public
    tables:
      - name: cert_dc_insern_2023_2024
      - name: cert_dc_insern_n2_n1
      - name: cert_dc_insern
      - name: dc_det
      - name: sa_esms
      - name: sa_hubee
      - name: sa_insee_histo
      - name: sa_pmsi
      - name: sa_rpu
      - name: sa_t_finess
      - name: sa_usld
      - name: v_commune_depuis
      - name: v_commune
      - name: v_departement
      - name: v_region
